notifications:
  email:
    on_success: never
    on_failure: always
os:
  - linux
  - osx
  - windows
language: python
python:
  - "3.8"
cache: pip
install:
  - pip install canaries
script:
  - python test.py
